version: "3.3"
services:
  influxdb:
    image: influxdb:1.8.2
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
  grafana:
    image: grafana/grafana:8.1.2
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./shared/grafana:/etc/grafana/provisioning/
  simulado:
    image : ldabiralai/simulado:latest
    platform: linux/amd64
    ports:
      - "3001:80"
    volumes:
      - ./shared/simulado:/app
    command: ./bin/simulado -f /app/mocks.json
  similar-product-finder:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

    container_name: similar-product-finder
    environment:
      SIMILAR_PRODUCTS_API_BASE_URL: http://simulado
      SIMILAR_PRODUCTS_API_CONNECT_TIMEOUT: 2s
      SIMILAR_PRODUCTS_API_READ_TIMEOUT: 6s
      SIMILAR_PRODUCTS_CACHE_ENABLED: "true"
      SIMILAR_PRODUCTS_CACHE_TTL: 5m
      SIMILAR_PRODUCTS_CACHE_NOT_FOUND_TTL: 1m
      RESILIENCE4J_BULKHEAD_PRODUCT_API_MAX_CONCURRENT: "150"
      RESILIENCE4J_BULKHEAD_PRODUCT_API_MAX_WAIT: 5ms
      RESILIENCE4J_CIRCUITBREAKER_INSTANCES_PRODUCT_API_SLIDING_WINDOW_TYPE: COUNT_BASED
      RESILIENCE4J_CIRCUITBREAKER_INSTANCES_PRODUCT_API_SLIDING_WINDOW_SIZE: "20"
      RESILIENCE4J_CIRCUITBREAKER_INSTANCES_PRODUCT_API_MINIMUM_NUMBER_OF_CALLS: "10"
      RESILIENCE4J_CIRCUITBREAKER_INSTANCES_PRODUCT_API_FAILURE_RATE_THRESHOLD: "50"
      RESILIENCE4J_CIRCUITBREAKER_INSTANCES_PRODUCT_API_SLOW_CALL_DURATION_THRESHOLD: 6s
      RESILIENCE4J_CIRCUITBREAKER_INSTANCES_PRODUCT_API_SLOW_CALL_RATE_THRESHOLD: "50"
      RESILIENCE4J_CIRCUITBREAKER_INSTANCES_PRODUCT_API_WAIT_DURATION_IN_OPEN_STATE: 10s
      RESILIENCE4J_CIRCUITBREAKER_INSTANCES_PRODUCT_API_PERMITTED_NUMBER_OF_CALLS_IN_HALF_OPEN_STATE: "3"
      SERVER_PORT: "5000"
    depends_on:
      - simulado
  k6:
    image: loadimpact/k6:0.28.0
    platform: linux/amd64
    ports:
      - "6565:6565"
    volumes:
      - ./shared/k6:/scripts
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    extra_hosts:
      - "host.docker.internal:host-gateway"
